import React,{useState} from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView,ScrollView,View,Text,TouchableOpacity,TextInput,StyleSheet,Alert,Image} from 'react-native';
import {StatusBar} from 'expo-status-bar';

const C={brown:'#4A2717',brown2:'#6A3A22',gold:'#C89A58',cream:'#FAF4E8',green:'#4E8A46',white:'#FFF',muted:'#786A61',ink:'#30241C'};
const IMG={
  porche:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-7.png',
  cenador:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/Cenadores-4-aguas.png',
  pergola:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-8.png',
  garaje:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-9.png',
  relax:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-1.png',
  caseta:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-10.png',
  terraza:'https://www.porchesdemaderabaratos.com/wp-content/uploads/2023/01/11-5.png'
};
const products=[
  {name:'Porche a un agua',price:'Desde 1.490 €',image:IMG.porche},
  {name:'Cenador 4 aguas',price:'Desde 2.390 €',image:IMG.cenador},
  {name:'Pérgola de madera',price:'Desde 990 €',image:IMG.pergola},
  {name:'Garaje de madera',price:'Desde 2.990 €',image:IMG.garaje}
];
const works=[
  {name:'Porche moderno',place:'Madrid',image:IMG.porche},
  {name:'Cenador de madera',place:'Toledo',image:IMG.cenador},
  {name:'Pérgola en terraza',place:'Madrid',image:IMG.pergola},
  {name:'Garaje de madera',place:'Madrid',image:IMG.garaje},
  {name:'Zona de relax',place:'Toledo',image:IMG.relax},
  {name:'Caseta de madera',place:'Madrid',image:IMG.caseta},
  {name:'Porche con teja',place:'Madrid',image:IMG.terraza}
];
function Page({children}){return <SafeAreaView style={{flex:1,backgroundColor:C.cream}}><ScrollView contentContainerStyle={s.body}>{children}</ScrollView></SafeAreaView>}
function Btn({title,onPress,light}){return <TouchableOpacity onPress={onPress} style={[s.btn,light&&s.btnLight]}><Text style={[s.btnText,light&&{color:C.brown}]}>{title}</Text></TouchableOpacity>}
function Home({navigation}){return <Page><View style={s.hero}><Text style={s.kicker}>MADRID · TOLEDO · TODA ESPAÑA</Text><Text style={s.hero1}>PORCHES DE MADERA</Text><Text style={s.hero2}>BARATOS</Text><Text style={s.heroSub}>Diseño, fabricación e instalación a medida.</Text><Btn title="PRESUPUESTO GRATIS" onPress={()=>navigation.navigate('Catálogo')}/></View><Text style={s.title}>Todo desde el móvil</Text>{['Presupuesto sin compromiso','Catálogo y precios orientativos','Seguimiento del trabajo','Galería de trabajos realizados','Reseñas destacadas'].map(x=><View key={x} style={s.card}><Text style={s.cardText}>✓ {x}</Text></View>)}<Btn title="WhatsApp · 603 686 893" onPress={()=>Alert.alert('WhatsApp','Contacto preparado para abrir WhatsApp.')}/></Page>}
function Catalog(){const [show,setShow]=useState(false);return <Page><Text style={s.title}>Catálogo y precios</Text><Text style={s.note}>Las imágenes y los precios se podrán cambiar desde el administrador cuando conectemos Supabase.</Text>{products.map(p=><View style={s.product} key={p.name}><Image source={{uri:p.image}} style={s.productImage}/><Text style={s.productName}>{p.name}</Text><Text style={s.price}>{p.price}</Text><Btn title="Pedir presupuesto" onPress={()=>setShow(true)}/></View>)}{show&&<View style={s.card}><Text style={s.productName}>Solicitud de presupuesto</Text>{['Nombre','Teléfono','Ciudad / Provincia','Cuéntanos tu idea'].map(x=><TextInput key={x} placeholder={x} style={s.input}/>)}<Btn title="Enviar solicitud" onPress={()=>{Alert.alert('Solicitud preparada','Al conectar Supabase se guardará y tendrá seguimiento.');setShow(false)}}/><Btn light title="Cancelar" onPress={()=>setShow(false)}/></View>}</Page>}
function Works(){return <Page><Text style={s.title}>Trabajos realizados</Text><Text style={s.note}>He añadido fotografías de la web actual como muestra. Después podrás añadir, sustituir u ordenar más imágenes desde administración.</Text><View style={s.grid}>{works.map((w,i)=><View key={w.name+i} style={s.work}><Image source={{uri:w.image}} style={s.workImg}/><Text style={s.workTitle}>{w.name}</Text><Text style={s.workText}>{w.place}</Text></View>)}</View></Page>}
function Tracking(){return <Page><Text style={s.title}>Seguimiento</Text><View style={s.card}><Text style={s.productName}>Nº PDM-2026-0048</Text>{['Solicitud recibida','Presupuesto confirmado','Fecha de instalación','Porche instalado'].map((x,i)=><View style={s.step} key={x}><View style={[s.dot,i<3&&{backgroundColor:C.green}]}><Text style={{color:'#fff'}}>{i<3?'✓':''}</Text></View><Text style={s.stepText}>{x}</Text></View>)}</View></Page>}
function Reviews(){return <Page><Text style={s.title}>Reseñas</Text>{[['Bea y Luis','Nuestra zona de relax ha quedado espectacular. Muy profesionales.'],['Carlos M.','Buen acabado, trato cercano y trabajo limpio.'],['María G.','El porche quedó justo como queríamos. Recomendables.']].map(([n,t])=><View style={s.card} key={n}><Text style={s.stars}>★★★★★</Text><Text style={s.review}>“{t}”</Text><Text style={s.reviewName}>{n}</Text></View>)}</Page>}
function Admin(){const [logged,setLogged]=useState(false);const [email,setEmail]=useState('');const [pass,setPass]=useState('');if(!logged)return <Page><Text style={s.title}>Administración</Text><View style={s.card}><Text style={s.productName}>Acceso privado</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" placeholder="Email administrador" style={s.input}/><TextInput value={pass} onChangeText={setPass} secureTextEntry placeholder="Contraseña" style={s.input}/><Btn title="Entrar" onPress={()=>{if(!email||!pass)return Alert.alert('Faltan datos');Alert.alert('Modo de prueba','La validación real quedará conectada a Supabase Auth.');setLogged(true)}}/></View></Page>;return <Page><Text style={s.title}>Panel de administración</Text>{['Productos, precios e imágenes','Pedidos / presupuestos','Trabajos realizados','Reseñas'].map(x=><View style={s.card} key={x}><Text style={s.productName}>{x}</Text><Text style={s.note}>Editar, añadir, sustituir, publicar y ordenar.</Text><Btn title="Gestionar" onPress={()=>Alert.alert(x,'Función preparada para la conexión definitiva con Supabase.')}/></View>)}<Btn light title="Cerrar sesión" onPress={()=>setLogged(false)}/></Page>}
const Tab=createBottomTabNavigator();
export default function App(){return <NavigationContainer><StatusBar style="light"/><Tab.Navigator screenOptions={({route})=>({headerStyle:{backgroundColor:C.brown2},headerTintColor:'#fff',tabBarActiveTintColor:C.brown2,tabBarInactiveTintColor:'#8b817a',tabBarLabelStyle:{fontSize:9},tabBarIcon:({color,size})=>{const m={Inicio:'home',Catálogo:'grid',Trabajos:'images',Seguimiento:'git-branch',Reseñas:'star',Admin:'settings'};return <Ionicons name={m[route.name]} size={size} color={color}/>;}})}><Tab.Screen name="Inicio" component={Home}/><Tab.Screen name="Catálogo" component={Catalog}/><Tab.Screen name="Trabajos" component={Works}/><Tab.Screen name="Seguimiento" component={Tracking}/><Tab.Screen name="Reseñas" component={Reviews}/><Tab.Screen name="Admin" component={Admin}/></Tab.Navigator></NavigationContainer>}
const s=StyleSheet.create({body:{padding:14,paddingBottom:40},hero:{backgroundColor:'#2C160C',padding:24,borderRadius:18,alignItems:'center',marginBottom:18},kicker:{color:C.gold,fontWeight:'800',fontSize:12},hero1:{color:'#DCA54F',fontSize:26,fontWeight:'900',marginTop:12,textAlign:'center'},hero2:{color:'#fff',fontSize:34,fontWeight:'900'},heroSub:{color:'#eadfd6',marginVertical:12,textAlign:'center'},title:{fontSize:23,fontWeight:'900',color:C.brown,marginBottom:12},note:{color:C.muted,lineHeight:20,marginBottom:10},card:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:12,elevation:2},cardText:{color:C.ink,fontSize:16,fontWeight:'700'},btn:{backgroundColor:C.green,padding:13,borderRadius:10,alignItems:'center',marginTop:8},btnLight:{backgroundColor:C.cream,borderWidth:1,borderColor:C.gold},btnText:{color:'#fff',fontWeight:'900'},product:{backgroundColor:'#fff',padding:13,borderRadius:14,marginBottom:12},productImage:{height:190,borderRadius:11,backgroundColor:'#D1A56B',resizeMode:'cover'},productName:{fontSize:17,fontWeight:'900',color:C.brown,marginTop:8},price:{fontWeight:'900',color:C.green,marginTop:4},input:{borderWidth:1,borderColor:'#decdb9',backgroundColor:'#fff',borderRadius:9,padding:11,marginTop:9},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},work:{width:'48%',backgroundColor:'#fff',borderRadius:13,padding:8,marginBottom:12},workImg:{width:'100%',height:140,borderRadius:10,backgroundColor:'#D1A56B',resizeMode:'cover'},workTitle:{fontWeight:'900',color:C.brown,marginTop:7},workText:{fontWeight:'700',color:C.muted,marginTop:3},step:{flexDirection:'row',alignItems:'center',marginVertical:14},dot:{width:36,height:36,borderRadius:18,backgroundColor:'#ccc',alignItems:'center',justifyContent:'center'},stepText:{marginLeft:12,fontSize:16,fontWeight:'800',color:C.ink},stars:{fontSize:24,color:'#D69B2D'},review:{fontSize:16,lineHeight:24,color:C.ink,marginVertical:8},reviewName:{fontWeight:'900',color:C.brown2}});
