import React,{useEffect,useState} from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {Ionicons} from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import {SafeAreaView,ScrollView,View,Text,TouchableOpacity,TextInput,StyleSheet,Alert,Image,ActivityIndicator,Linking} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {supabase} from './supabase';

const C={brown:'#4A2717',brown2:'#6A3A22',gold:'#C89A58',cream:'#FAF4E8',green:'#4E8A46',white:'#FFF',muted:'#786A61',ink:'#30241C',danger:'#A13C34'};
const PHONE='34603686893';
const WEB='https://www.porchesdemaderabaratos.com';
const PRIVACY=`${WEB}/politica-de-privacidad/`;
const LEGAL=`${WEB}/aviso-legal/`;
const FALLBACK_CATALOG=[
 {id:'f1',nombre:'Porche a un agua',descripcion:'Porche de madera a medida.',precio_desde:null,imagen_url:`${WEB}/wp-content/uploads/2023/01/11-7.png`},
 {id:'f2',nombre:'Pérgola de madera',descripcion:'Pérgola de madera a medida.',precio_desde:null,imagen_url:`${WEB}/wp-content/uploads/2023/01/11-8.png`},
 {id:'f3',nombre:'Cenador a 4 aguas',descripcion:'Cenador de madera a medida.',precio_desde:null,imagen_url:`${WEB}/wp-content/uploads/2023/01/Cenadores-4-aguas.png`},
 {id:'f4',nombre:'Garaje de madera',descripcion:'Garaje de madera a medida.',precio_desde:null,imagen_url:`${WEB}/wp-content/uploads/2023/01/11-9.png`}
];
const FALLBACK_WORKS=[
 {id:'w1',titulo:'Porche a un agua',ubicacion:'Madrid',imagen_url:`${WEB}/wp-content/uploads/2023/01/11-7.png`},
 {id:'w2',titulo:'Pérgola de madera',ubicacion:'Toledo',imagen_url:`${WEB}/wp-content/uploads/2023/01/11-8.png`},
 {id:'w3',titulo:'Garaje de madera',ubicacion:'Madrid',imagen_url:`${WEB}/wp-content/uploads/2023/01/11-9.png`},
 {id:'w4',titulo:'Porche independiente',ubicacion:'España',imagen_url:`${WEB}/wp-content/uploads/2023/01/11-5.png`}
];
const FALLBACK_REVIEWS=[{id:'r1',nombre:'Bea y Luis',estrellas:5,texto:'¡Nuestra zona de relax ha quedado espectacular! Muy profesionales. 100% recomendados.'}];

const normalizePhone=(value='')=>{let d=String(value).replace(/\D/g,'');if(d.length===9)d=`34${d}`;return d;};
const openWhatsApp=(text='Hola, quiero información sobre un porche de madera.')=>Linking.openURL(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`);
function Page({children}){return <SafeAreaView style={{flex:1,backgroundColor:C.cream}}><ScrollView contentContainerStyle={s.body}>{children}</ScrollView></SafeAreaView>}
function Btn({title,onPress,light,danger,disabled}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.btn,light&&s.btnLight,danger&&{backgroundColor:C.danger},disabled&&{opacity:.5}]}><Text style={[s.btnText,light&&{color:C.brown}]}>{title}</Text></TouchableOpacity>}
function Field({placeholder,value,onChangeText,secureTextEntry,multiline,keyboardType,autoCapitalize='sentences'}){return <TextInput placeholder={placeholder} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} multiline={multiline} keyboardType={keyboardType} autoCapitalize={autoCapitalize} style={[s.input,multiline&&{minHeight:90,textAlignVertical:'top'}]}/>}
function Loader(){return <View style={{padding:30}}><ActivityIndicator size="large" color={C.brown2}/></View>}
function Check({value,onPress,label}){return <TouchableOpacity onPress={onPress} style={s.checkRow}><View style={[s.check,value&&s.checkOn]}>{value?<Text style={s.checkMark}>✓</Text>:null}</View><Text style={s.checkText}>{label}</Text></TouchableOpacity>}

function Home({navigation}){return <Page><View style={s.hero}><Text style={s.kicker}>MADRID · TOLEDO · TODA ESPAÑA</Text><Text style={s.hero1}>PORCHES DE MADERA</Text><Text style={s.hero2}>BARATOS</Text><Text style={s.heroSub}>Diseño, fabricación e instalación a medida.</Text><Btn title="PRESUPUESTO GRATIS" onPress={()=>navigation.navigate('Catálogo')}/></View><Text style={s.title}>Todo desde el móvil</Text>{['Presupuesto sin compromiso','Catálogo actualizado','Seguimiento del trabajo','Galería de trabajos realizados','Reseñas destacadas'].map(x=><View key={x} style={s.card}><Text style={s.cardText}>✓ {x}</Text></View>)}<Btn title="WhatsApp · 603 686 893" onPress={()=>openWhatsApp()}/><View style={s.card}><Text style={s.productName}>Información y privacidad</Text><Text style={s.note}>Los datos que facilites se usan para atender tu solicitud de presupuesto y realizar su seguimiento. No se utilizan para publicidad sin una base legal adecuada.</Text><Btn light title="Política de privacidad" onPress={()=>Linking.openURL(PRIVACY)}/><Btn light title="Aviso legal" onPress={()=>Linking.openURL(LEGAL)}/></View></Page>}

function Catalog(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[selected,setSelected]=useState(null);
 const [nombre,setNombre]=useState(''),[telefono,setTelefono]=useState(''),[ciudad,setCiudad]=useState(''),[descripcion,setDescripcion]=useState(''),[informed,setInformed]=useState(false);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('catalogo').select('*').eq('activo',true).order('orden');setItems(error||!data?.length?FALLBACK_CATALOG:data);setLoading(false)};
 useEffect(()=>{load()},[]);
 const send=async()=>{
  if(!nombre.trim()||!telefono.trim())return Alert.alert('Faltan datos','Escribe nombre y teléfono.');
  if(!informed)return Alert.alert('Privacidad','Confirma que has sido informado sobre el tratamiento de tus datos.');
  const code=`PMB-${Date.now().toString().slice(-8)}-${Math.floor(Math.random()*900+100)}`;
  const tipo=selected?.nombre||'Presupuesto general';
  const payload={codigo_seguimiento:code,nombre:nombre.trim(),telefono:telefono.trim(),ciudad:ciudad.trim()||null,tipo_trabajo:tipo,descripcion:descripcion.trim()||null};
  const {error}=await supabase.from('solicitudes').insert(payload);
  const mensaje=`Hola, quiero solicitar un presupuesto desde la app de Porches de Madera Baratos.\n\nCódigo: ${code}\nNombre: ${nombre.trim()}\nTeléfono: ${telefono.trim()}\nCiudad / Provincia: ${ciudad.trim()||'No indicada'}\nTrabajo: ${tipo}\nDescripción: ${descripcion.trim()||'Sin descripción adicional'}\n\nQuedo a la espera de información y presupuesto. Gracias.`;
  if(error)Alert.alert('Seguimiento no guardado','Abriremos WhatsApp igualmente. Guarda el código de solicitud por si necesitas consultarlo: '+code);
  setShow(false);setNombre('');setTelefono('');setCiudad('');setDescripcion('');setInformed(false);
  try{await openWhatsApp(mensaje)}catch(e){Alert.alert('Solicitud preparada',`Código: ${code}. No se pudo abrir WhatsApp automáticamente.`)}
 };
 return <Page><Text style={s.title}>Catálogo y precios</Text><Text style={s.note}>Imágenes orientativas. El precio final se confirma mediante presupuesto personalizado.</Text>{loading?<Loader/>:items.map(p=><View style={s.product} key={p.id}>{p.imagen_url?<Image source={{uri:p.imagen_url}} style={s.productImage}/>:null}<Text style={s.productName}>{p.nombre}</Text>{p.descripcion?<Text style={s.note}>{p.descripcion}</Text>:null}<Text style={s.price}>{p.precio_desde?`Desde ${Number(p.precio_desde).toLocaleString('es-ES')} €`:'Consultar precio'}</Text><Btn title="Pedir presupuesto" onPress={()=>{setSelected(p);setShow(true)}}/></View>)}{show&&<View style={s.card}>{selected?.imagen_url?<Image source={{uri:selected.imagen_url}} style={s.productImage}/>:null}<Text style={s.productName}>Solicitud: {selected?.nombre||'Presupuesto'}</Text><Text style={s.note}>Solicitar presupuesto no implica compra ni obligación de pago.</Text><Field placeholder="Nombre y apellidos" value={nombre} onChangeText={setNombre}/><Field placeholder="Teléfono" value={telefono} onChangeText={setTelefono} keyboardType="phone-pad"/><Field placeholder="Ciudad / Provincia" value={ciudad} onChangeText={setCiudad}/><Field placeholder="Cuéntanos tu idea" value={descripcion} onChangeText={setDescripcion} multiline/><Check value={informed} onPress={()=>setInformed(v=>!v)} label="He sido informado sobre el tratamiento de mis datos para gestionar esta solicitud."/><TouchableOpacity onPress={()=>Linking.openURL(PRIVACY)}><Text style={s.link}>Ver política de privacidad</Text></TouchableOpacity><Btn title="Enviar solicitud y abrir WhatsApp" onPress={send}/><Btn light title="Cancelar" onPress={()=>setShow(false)}/></View>}</Page>}

function Works(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data,error}=await supabase.from('trabajos_realizados').select('*').eq('publicado',true).order('created_at',{ascending:false});setItems(error||!data?.length?FALLBACK_WORKS:data);setLoading(false)})()},[]);return <Page><Text style={s.title}>Trabajos realizados</Text>{loading?<Loader/>:<View style={s.grid}>{items.map(w=><View key={w.id} style={s.work}>{w.imagen_url?<Image source={{uri:w.imagen_url}} style={s.workImg}/>:null}<Text style={s.workTitle}>{w.titulo}</Text><Text style={s.workText}>{w.ubicacion||''}</Text></View>)}</View>}</Page>}

function Tracking(){const [code,setCode]=useState(''),[phone,setPhone]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false);const lookup=async()=>{if(!code||!phone)return Alert.alert('Faltan datos');setLoading(true);const {data,error}=await supabase.functions.invoke('tracking_lookup',{body:{codigo:code.trim(),telefono:phone.trim()}});setLoading(false);if(error||!data?.ok){setResult(null);return Alert.alert('No encontrado','Comprueba el código y el teléfono.')}setResult(data.solicitud)};return <Page><Text style={s.title}>Seguimiento</Text><View style={s.card}><Field placeholder="Código PMB-..." value={code} onChangeText={setCode} autoCapitalize="characters"/><Field placeholder="Teléfono usado en la solicitud" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Btn title={loading?'Consultando...':'Consultar estado'} onPress={lookup} disabled={loading}/></View>{result&&<View style={s.card}><Text style={s.productName}>{result.codigo_seguimiento}</Text><Text style={s.status}>{result.estado}</Text><Text style={s.note}>{result.tipo_trabajo||''}</Text><Text style={s.note}>{result.admin_notas||'Sin observaciones nuevas.'}</Text><Btn title="Contactar por WhatsApp" onPress={()=>openWhatsApp(`Hola, consulto mi solicitud ${result.codigo_seguimiento}.`)}/></View>}</Page>}

function Reviews(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data,error}=await supabase.from('resenas').select('*').eq('publicado',true).order('created_at',{ascending:false});setItems(error||!data?.length?FALLBACK_REVIEWS:data);setLoading(false)})()},[]);return <Page><Text style={s.title}>Reseñas</Text>{loading?<Loader/>:items.map(r=><View style={s.card} key={r.id}><Text style={s.stars}>{'★'.repeat(Math.max(1,Math.min(5,Number(r.estrellas)||5)))}</Text><Text style={s.review}>“{r.texto}”</Text><Text style={s.reviewName}>{r.nombre}</Text></View>)}</Page>}

function Legal(){return <Page><Text style={s.title}>Información legal</Text><View style={s.card}><Text style={s.productName}>Porches de Madera Baratos</Text><Text style={s.note}>Teléfono: +34 603 686 893</Text><Text style={s.note}>Email: info@porchesdemaderabaratos.com</Text><Text style={s.note}>Madrid, España</Text><Text style={s.note}>La solicitud de presupuesto desde esta app es gratuita y no genera por sí sola una obligación de compra o pago. Las condiciones, precio final, impuestos, plazos, instalación y demás información precontractual se concretarán antes de cualquier contratación.</Text><Btn light title="Aviso legal" onPress={()=>Linking.openURL(LEGAL)}/><Btn light title="Política de privacidad" onPress={()=>Linking.openURL(PRIVACY)}/><Btn light title="Web oficial" onPress={()=>Linking.openURL(WEB)}/></View></Page>}

function Admin(){
 const [session,setSession]=useState(null),[isAdmin,setIsAdmin]=useState(false),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[loading,setLoading]=useState(true);
 const [products,setProducts]=useState([]),[requests,setRequests]=useState([]),[reviews,setReviews]=useState([]),[works,setWorks]=useState([]),[section,setSection]=useState('productos');
 const [edit,setEdit]=useState(null),[name,setName]=useState(''),[category,setCategory]=useState('Porches'),[price,setPrice]=useState(''),[desc,setDesc]=useState(''),[imageUrl,setImageUrl]=useState('');
 const [workEdit,setWorkEdit]=useState(null),[workTitle,setWorkTitle]=useState(''),[workLocation,setWorkLocation]=useState(''),[workDesc,setWorkDesc]=useState(''),[workImage,setWorkImage]=useState('');
 const [reviewEdit,setReviewEdit]=useState(null),[reviewName,setReviewName]=useState(''),[reviewText,setReviewText]=useState(''),[reviewStars,setReviewStars]=useState('5');
 const refresh=async()=>{const [p,q,r,w]=await Promise.all([supabase.from('catalogo').select('*').order('orden'),supabase.from('solicitudes').select('*').order('created_at',{ascending:false}),supabase.from('resenas').select('*').order('created_at',{ascending:false}),supabase.from('trabajos_realizados').select('*').order('created_at',{ascending:false})]);setProducts(p.data||[]);setRequests(q.data||[]);setReviews(r.data||[]);setWorks(w.data||[])};
 const verify=async(ses)=>{if(!ses){setSession(null);setIsAdmin(false);setLoading(false);return}const {data,error}=await supabase.from('admins').select('user_id').eq('user_id',ses.user.id).maybeSingle();setSession(ses);setIsAdmin(!error&&!!data);if(data)await refresh();setLoading(false)};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>verify(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,ses)=>verify(ses));return()=>subscription.unsubscribe()},[]);
 const login=async()=>{if(!email.trim()||!pass)return Alert.alert('Faltan datos','Escribe email y contraseña.');setLoading(true);const {data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password:pass});if(error){setLoading(false);return Alert.alert('Acceso denegado','Usuario o contraseña incorrectos.')}await verify(data.session)};
 const logout=async()=>{await supabase.auth.signOut();setSession(null);setIsAdmin(false)};
 const uploadImage=async(bucket,setter)=>{const res=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.85});if(res.canceled)return;const asset=res.assets[0];try{const body=await (await fetch(asset.uri)).arrayBuffer();const ext=(asset.fileName?.split('.').pop()||'jpg').toLowerCase();const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,body,{contentType:asset.mimeType||'image/jpeg'});if(error)throw error;const {data}=supabase.storage.from(bucket).getPublicUrl(path);setter(data.publicUrl)}catch(e){Alert.alert('Error de imagen',e.message)}};
 const clearProduct=()=>{setEdit(null);setName('');setCategory('Porches');setPrice('');setDesc('');setImageUrl('')};
 const saveProduct=async()=>{if(!name.trim())return Alert.alert('Falta el nombre');const payload={nombre:name.trim(),categoria:category.trim()||'Porches',descripcion:desc.trim()||null,precio_desde:price?Number(String(price).replace(',','.')):null,imagen_url:imageUrl||null,activo:true};const op=edit?supabase.from('catalogo').update(payload).eq('id',edit.id):supabase.from('catalogo').insert(payload);const {error}=await op;if(error)return Alert.alert('Error',error.message);clearProduct();await refresh()};
 const editProduct=p=>{setEdit(p);setName(p.nombre||'');setCategory(p.categoria||'Porches');setPrice(p.precio_desde?String(p.precio_desde):'');setDesc(p.descripcion||'');setImageUrl(p.imagen_url||'')};
 const delProduct=async p=>{const {error}=await supabase.from('catalogo').delete().eq('id',p.id);if(error)Alert.alert('Error',error.message);else refresh()};
 const setStatus=async(q,estado)=>{const {error}=await supabase.from('solicitudes').update({estado,updated_at:new Date().toISOString()}).eq('id',q.id);if(error)Alert.alert('Error',error.message);else refresh()};
 const clearWork=()=>{setWorkEdit(null);setWorkTitle('');setWorkLocation('');setWorkDesc('');setWorkImage('')};
 const saveWork=async()=>{if(!workTitle.trim()||!workImage)return Alert.alert('Faltan datos','Añade título e imagen.');const payload={titulo:workTitle.trim(),ubicacion:workLocation.trim()||null,descripcion:workDesc.trim()||null,imagen_url:workImage,publicado:true};const op=workEdit?supabase.from('trabajos_realizados').update(payload).eq('id',workEdit.id):supabase.from('trabajos_realizados').insert(payload);const {error}=await op;if(error)return Alert.alert('Error',error.message);clearWork();await refresh()};
 const editWork=w=>{setWorkEdit(w);setWorkTitle(w.titulo||'');setWorkLocation(w.ubicacion||'');setWorkDesc(w.descripcion||'');setWorkImage(w.imagen_url||'')};
 const delWork=async w=>{const {error}=await supabase.from('trabajos_realizados').delete().eq('id',w.id);if(error)Alert.alert('Error',error.message);else refresh()};
 const clearReview=()=>{setReviewEdit(null);setReviewName('');setReviewText('');setReviewStars('5')};
 const saveReview=async()=>{const stars=Math.max(1,Math.min(5,Number(reviewStars)||5));if(!reviewName.trim()||!reviewText.trim())return Alert.alert('Faltan datos','Añade nombre y reseña.');const payload={nombre:reviewName.trim(),texto:reviewText.trim(),estrellas:stars,publicado:true};const op=reviewEdit?supabase.from('resenas').update(payload).eq('id',reviewEdit.id):supabase.from('resenas').insert(payload);const {error}=await op;if(error)return Alert.alert('Error',error.message);clearReview();await refresh()};
 const editReview=r=>{setReviewEdit(r);setReviewName(r.nombre||'');setReviewText(r.texto||'');setReviewStars(String(r.estrellas||5))};
 const delReview=async r=>{const {error}=await supabase.from('resenas').delete().eq('id',r.id);if(error)Alert.alert('Error',error.message);else refresh()};
 if(loading)return <Page><Loader/></Page>;
 if(!session||!isAdmin)return <Page><Text style={s.title}>Administración</Text><View style={s.card}><Text style={s.productName}>Acceso privado</Text><Text style={s.note}>Solo la cuenta autorizada puede modificar contenido y solicitudes.</Text><Field placeholder="Email administrador" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field placeholder="Contraseña" value={pass} onChangeText={setPass} secureTextEntry autoCapitalize="none"/><Btn title="Entrar" onPress={login}/></View></Page>;
 return <Page><Text style={s.title}>Panel de administración</Text><View style={s.tabs}>{['productos','pedidos','trabajos','reseñas'].map(x=><TouchableOpacity key={x} onPress={()=>setSection(x)} style={[s.tab,section===x&&s.tabOn]}><Text style={[s.tabText,section===x&&{color:'#fff'}]}>{x.toUpperCase()}</Text></TouchableOpacity>)}</View>
 {section==='productos'&&<><View style={s.card}><Text style={s.productName}>{edit?'Editar producto':'Añadir producto'}</Text><Field placeholder="Nombre" value={name} onChangeText={setName}/><Field placeholder="Categoría" value={category} onChangeText={setCategory}/><Field placeholder="Precio desde" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/><Field placeholder="Descripción" value={desc} onChangeText={setDesc} multiline/><Btn light title="Elegir imagen" onPress={()=>uploadImage('catalogo',setImageUrl)}/>{imageUrl?<Image source={{uri:imageUrl}} style={s.productImage}/>:null}<Btn title={edit?'Guardar cambios':'Añadir producto'} onPress={saveProduct}/>{edit?<Btn light title="Cancelar edición" onPress={clearProduct}/>:null}</View>{products.map(p=><View style={s.card} key={p.id}>{p.imagen_url?<Image source={{uri:p.imagen_url}} style={s.smallImage}/>:null}<Text style={s.productName}>{p.nombre}</Text><Text style={s.note}>{p.precio_desde?`${p.precio_desde} €`:'Sin precio'}</Text><Btn title="Editar" onPress={()=>editProduct(p)}/><Btn danger title="Eliminar" onPress={()=>delProduct(p)}/></View>)}</>}
 {section==='pedidos'&&<>{requests.length?requests.map(q=><View style={s.card} key={q.id}><Text style={s.productName}>{q.nombre} · {q.codigo_seguimiento}</Text><Text style={s.note}>{q.telefono} · {q.ciudad||''}</Text><Text style={s.note}>{q.tipo_trabajo||''}</Text><Text style={s.status}>{q.estado}</Text><Btn title="Presupuesto confirmado" onPress={()=>setStatus(q,'Presupuesto confirmado')}/><Btn light title="Fecha de instalación" onPress={()=>setStatus(q,'Fecha de instalación')}/><Btn light title="Porche instalado" onPress={()=>setStatus(q,'Porche instalado')}/><Btn title="WhatsApp cliente" onPress={()=>Linking.openURL(`https://wa.me/${normalizePhone(q.telefono)}`)}/></View>):<View style={s.card}><Text style={s.note}>Todavía no hay solicitudes.</Text></View>}</>}
 {section==='trabajos'&&<><View style={s.card}><Text style={s.productName}>{workEdit?'Editar trabajo':'Añadir trabajo realizado'}</Text><Field placeholder="Título" value={workTitle} onChangeText={setWorkTitle}/><Field placeholder="Ubicación" value={workLocation} onChangeText={setWorkLocation}/><Field placeholder="Descripción" value={workDesc} onChangeText={setWorkDesc} multiline/><Btn light title="Elegir foto" onPress={()=>uploadImage('trabajos-fotos',setWorkImage)}/>{workImage?<Image source={{uri:workImage}} style={s.productImage}/>:null}<Btn title={workEdit?'Guardar trabajo':'Publicar trabajo'} onPress={saveWork}/>{workEdit?<Btn light title="Cancelar edición" onPress={clearWork}/>:null}</View>{works.map(w=><View style={s.card} key={w.id}>{w.imagen_url?<Image source={{uri:w.imagen_url}} style={s.productImage}/>:null}<Text style={s.productName}>{w.titulo}</Text><Text style={s.note}>{w.ubicacion||''}</Text><Btn title="Editar" onPress={()=>editWork(w)}/><Btn danger title="Eliminar" onPress={()=>delWork(w)}/></View>)}</>}
 {section==='reseñas'&&<><View style={s.card}><Text style={s.productName}>{reviewEdit?'Editar reseña':'Añadir reseña'}</Text><Field placeholder="Nombre del cliente" value={reviewName} onChangeText={setReviewName}/><Field placeholder="Reseña" value={reviewText} onChangeText={setReviewText} multiline/><Field placeholder="Estrellas 1-5" value={reviewStars} onChangeText={setReviewStars} keyboardType="number-pad"/><Btn title={reviewEdit?'Guardar reseña':'Publicar reseña'} onPress={saveReview}/>{reviewEdit?<Btn light title="Cancelar edición" onPress={clearReview}/>:null}</View>{reviews.map(r=><View style={s.card} key={r.id}><Text style={s.stars}>{'★'.repeat(Math.max(1,Math.min(5,Number(r.estrellas)||5)))}</Text><Text style={s.review}>{r.texto}</Text><Text style={s.reviewName}>{r.nombre}</Text><Btn title="Editar" onPress={()=>editReview(r)}/><Btn danger title="Eliminar" onPress={()=>delReview(r)}/></View>)}</>}
 <Btn light title="Actualizar datos" onPress={refresh}/><Btn danger title="Cerrar sesión" onPress={logout}/></Page>}

const Tab=createBottomTabNavigator();
export default function App(){return <NavigationContainer><StatusBar style="light"/><Tab.Navigator screenOptions={({route})=>({headerStyle:{backgroundColor:C.brown2},headerTintColor:'#fff',tabBarActiveTintColor:C.brown2,tabBarInactiveTintColor:'#8b817a',tabBarLabelStyle:{fontSize:8},tabBarIcon:({color,size})=>{const m={Inicio:'home',Catálogo:'grid',Trabajos:'images',Seguimiento:'git-branch',Reseñas:'star',Legal:'shield-checkmark',Admin:'settings'};return <Ionicons name={m[route.name]} size={size} color={color}/>;}})}><Tab.Screen name="Inicio" component={Home}/><Tab.Screen name="Catálogo" component={Catalog}/><Tab.Screen name="Trabajos" component={Works}/><Tab.Screen name="Seguimiento" component={Tracking}/><Tab.Screen name="Reseñas" component={Reviews}/><Tab.Screen name="Legal" component={Legal}/><Tab.Screen name="Admin" component={Admin}/></Tab.Navigator></NavigationContainer>}

const s=StyleSheet.create({body:{padding:14,paddingBottom:40},hero:{backgroundColor:'#2C160C',padding:24,borderRadius:18,alignItems:'center',marginBottom:18},kicker:{color:C.gold,fontWeight:'800',fontSize:12},hero1:{color:'#DCA54F',fontSize:26,fontWeight:'900',marginTop:12,textAlign:'center'},hero2:{color:'#fff',fontSize:34,fontWeight:'900'},heroSub:{color:'#eadfd6',marginVertical:12,textAlign:'center'},title:{fontSize:23,fontWeight:'900',color:C.brown,marginBottom:12},note:{color:C.muted,lineHeight:20,marginBottom:10},card:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:12,elevation:2},cardText:{color:C.ink,fontSize:16,fontWeight:'700'},btn:{backgroundColor:C.green,padding:13,borderRadius:10,alignItems:'center',marginTop:8},btnLight:{backgroundColor:C.cream,borderWidth:1,borderColor:C.gold},btnText:{color:'#fff',fontWeight:'900'},product:{backgroundColor:'#fff',padding:13,borderRadius:14,marginBottom:12},productImage:{height:190,width:'100%',borderRadius:11,backgroundColor:'#D1A56B',resizeMode:'cover',marginTop:8},smallImage:{height:110,width:'100%',borderRadius:10,resizeMode:'cover'},productName:{fontSize:17,fontWeight:'900',color:C.brown,marginTop:8},price:{fontWeight:'900',color:C.green,marginTop:4},input:{borderWidth:1,borderColor:'#decdb9',backgroundColor:'#fff',borderRadius:9,padding:11,marginTop:9},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},work:{width:'48%',backgroundColor:'#fff',borderRadius:13,padding:8,marginBottom:12},workImg:{width:'100%',height:140,borderRadius:10,backgroundColor:'#D1A56B',resizeMode:'cover'},workTitle:{fontWeight:'900',color:C.brown,marginTop:7},workText:{fontWeight:'700',color:C.muted,marginTop:3},stars:{fontSize:24,color:'#D69B2D'},review:{fontSize:16,lineHeight:24,color:C.ink,marginVertical:8},reviewName:{fontWeight:'900',color:C.brown2},status:{fontSize:17,fontWeight:'900',color:C.green,marginVertical:6},tabs:{flexDirection:'row',flexWrap:'wrap',marginBottom:12},tab:{paddingVertical:9,paddingHorizontal:10,backgroundColor:'#fff',borderRadius:10,marginRight:6,marginBottom:6},tabOn:{backgroundColor:C.brown2},tabText:{fontWeight:'900',fontSize:11,color:C.brown},checkRow:{flexDirection:'row',alignItems:'flex-start',marginTop:14},check:{width:24,height:24,borderWidth:2,borderColor:C.brown2,borderRadius:5,marginRight:9,alignItems:'center',justifyContent:'center'},checkOn:{backgroundColor:C.green,borderColor:C.green},checkMark:{color:'#fff',fontWeight:'900'},checkText:{flex:1,color:C.ink,lineHeight:20},link:{color:C.brown2,textDecorationLine:'underline',fontWeight:'800',marginTop:8}});
