import React,{useEffect,useState} from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {Ionicons} from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import {SafeAreaView,ScrollView,View,Text,TouchableOpacity,TextInput,StyleSheet,Alert,Image,ActivityIndicator,Linking} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {supabase} from './supabase';

const C={brown:'#4A2717',brown2:'#6A3A22',gold:'#C89A58',cream:'#FAF4E8',green:'#4E8A46',white:'#FFF',muted:'#786A61',ink:'#30241C',danger:'#A13C34'};
const PHONE='34603686893';
const openWhatsApp=(text='Hola, quiero información sobre un porche de madera.')=>Linking.openURL(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`);
function Page({children}){return <SafeAreaView style={{flex:1,backgroundColor:C.cream}}><ScrollView contentContainerStyle={s.body}>{children}</ScrollView></SafeAreaView>}
function Btn({title,onPress,light,danger,disabled}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.btn,light&&s.btnLight,danger&&{backgroundColor:C.danger},disabled&&{opacity:.5}]}><Text style={[s.btnText,light&&{color:C.brown}]}>{title}</Text></TouchableOpacity>}
function Field({placeholder,value,onChangeText,secureTextEntry,multiline,keyboardType}){return <TextInput placeholder={placeholder} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} multiline={multiline} keyboardType={keyboardType} autoCapitalize="none" style={[s.input,multiline&&{minHeight:90,textAlignVertical:'top'}]}/>}
function Loader(){return <View style={{padding:30}}><ActivityIndicator size="large" color={C.brown2}/></View>}

function Home({navigation}){return <Page><View style={s.hero}><Text style={s.kicker}>MADRID · TOLEDO · TODA ESPAÑA</Text><Text style={s.hero1}>PORCHES DE MADERA</Text><Text style={s.hero2}>BARATOS</Text><Text style={s.heroSub}>Diseño, fabricación e instalación a medida.</Text><Btn title="PRESUPUESTO GRATIS" onPress={()=>navigation.navigate('Catálogo')}/></View><Text style={s.title}>Todo desde el móvil</Text>{['Presupuesto sin compromiso','Catálogo actualizado','Seguimiento del trabajo','Galería de trabajos realizados','Reseñas destacadas'].map(x=><View key={x} style={s.card}><Text style={s.cardText}>✓ {x}</Text></View>)}<Btn title="WhatsApp · 603 686 893" onPress={()=>openWhatsApp()}/></Page>}

function Catalog(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[selected,setSelected]=useState(null);
 const [nombre,setNombre]=useState(''),[telefono,setTelefono]=useState(''),[ciudad,setCiudad]=useState(''),[descripcion,setDescripcion]=useState('');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('catalogo').select('*').eq('activo',true).order('orden');if(error)Alert.alert('Error',error.message);else setItems(data||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const send=async()=>{
  if(!nombre||!telefono)return Alert.alert('Faltan datos','Escribe nombre y teléfono.');
  const code=`PMB-${Date.now().toString().slice(-8)}-${Math.floor(Math.random()*900+100)}`;
  const tipo=selected?.nombre||'Presupuesto general';
  const {error}=await supabase.from('solicitudes').insert({codigo_seguimiento:code,nombre,telefono,ciudad,tipo_trabajo:tipo,descripcion});
  if(error)return Alert.alert('No se pudo enviar',error.message);
  const mensaje=`Hola, quiero solicitar un presupuesto desde la app de Porches de Madera Baratos.\n\nCódigo: ${code}\nNombre: ${nombre}\nTeléfono: ${telefono}\nCiudad / Provincia: ${ciudad||'No indicada'}\nTrabajo: ${tipo}\nDescripción: ${descripcion||'Sin descripción adicional'}\n\nQuedo a la espera de información y presupuesto. Gracias.`;
  setShow(false);setNombre('');setTelefono('');setCiudad('');setDescripcion('');
  try{await openWhatsApp(mensaje)}catch(e){Alert.alert('Solicitud guardada',`Tu solicitud se guardó correctamente. Código: ${code}. No se pudo abrir WhatsApp automáticamente.`)}
 };
 return <Page><Text style={s.title}>Catálogo y precios</Text><Text style={s.note}>Modelos, imágenes y precios gestionados desde administración.</Text>{loading?<Loader/>:items.map(p=><View style={s.product} key={p.id}>{p.imagen_url?<Image source={{uri:p.imagen_url}} style={s.productImage}/>:null}<Text style={s.productName}>{p.nombre}</Text>{p.descripcion?<Text style={s.note}>{p.descripcion}</Text>:null}<Text style={s.price}>{p.precio_desde?`Desde ${Number(p.precio_desde).toLocaleString('es-ES')} €`:'Consultar precio'}</Text><Btn title="Pedir presupuesto" onPress={()=>{setSelected(p);setShow(true)}}/></View>)}{show&&<View style={s.card}><Text style={s.productName}>Solicitud: {selected?.nombre||'Presupuesto'}</Text><Field placeholder="Nombre y apellidos" value={nombre} onChangeText={setNombre}/><Field placeholder="Teléfono" value={telefono} onChangeText={setTelefono} keyboardType="phone-pad"/><Field placeholder="Ciudad / Provincia" value={ciudad} onChangeText={setCiudad}/><Field placeholder="Cuéntanos tu idea" value={descripcion} onChangeText={setDescripcion} multiline/><Btn title="Enviar y abrir WhatsApp" onPress={send}/><Btn light title="Cancelar" onPress={()=>setShow(false)}/></View>}</Page>}

function Works(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data}=await supabase.from('trabajos_realizados').select('*').eq('publicado',true).order('created_at',{ascending:false});setItems(data||[]);setLoading(false)})()},[]);return <Page><Text style={s.title}>Trabajos realizados</Text>{loading?<Loader/>:items.length? <View style={s.grid}>{items.map(w=><View key={w.id} style={s.work}><Image source={{uri:w.imagen_url}} style={s.workImg}/><Text style={s.workTitle}>{w.titulo}</Text><Text style={s.workText}>{w.ubicacion||''}</Text></View>)}</View>:<View style={s.card}><Text style={s.note}>Las nuevas fotografías publicadas por el administrador aparecerán aquí.</Text></View>}</Page>}

function Tracking(){const [code,setCode]=useState(''),[phone,setPhone]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false);const lookup=async()=>{if(!code||!phone)return Alert.alert('Faltan datos');setLoading(true);const {data,error}=await supabase.functions.invoke('tracking_lookup',{body:{codigo:code.trim(),telefono:phone.trim()}});setLoading(false);if(error||!data?.ok){setResult(null);return Alert.alert('No encontrado','Comprueba el código y el teléfono.')}setResult(data.solicitud)};return <Page><Text style={s.title}>Seguimiento</Text><View style={s.card}><Field placeholder="Código PMB-..." value={code} onChangeText={setCode}/><Field placeholder="Teléfono usado en la solicitud" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Btn title={loading?'Consultando...':'Consultar estado'} onPress={lookup} disabled={loading}/></View>{result&&<View style={s.card}><Text style={s.productName}>{result.codigo_seguimiento}</Text><Text style={s.status}>{result.estado}</Text><Text style={s.note}>{result.tipo_trabajo||''}</Text><Text style={s.note}>{result.admin_notas||'Sin observaciones nuevas.'}</Text><Btn title="Contactar por WhatsApp" onPress={()=>openWhatsApp(`Hola, consulto mi solicitud ${result.codigo_seguimiento}.`)}/></View>}</Page>}

function Reviews(){const [items,setItems]=useState([]);useEffect(()=>{(async()=>{const {data}=await supabase.from('resenas').select('*').eq('publicado',true).order('created_at',{ascending:false});setItems(data||[])})()},[]);return <Page><Text style={s.title}>Reseñas</Text>{items.map(r=><View style={s.card} key={r.id}><Text style={s.stars}>{'★'.repeat(r.estrellas)}</Text><Text style={s.review}>“{r.texto}”</Text><Text style={s.reviewName}>{r.nombre}</Text></View>)}</Page>}

function Admin(){
 const [session,setSession]=useState(null),[isAdmin,setIsAdmin]=useState(false),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[loading,setLoading]=useState(true);
 const [products,setProducts]=useState([]),[requests,setRequests]=useState([]),[reviews,setReviews]=useState([]),[works,setWorks]=useState([]),[section,setSection]=useState('productos');
 const [edit,setEdit]=useState(null),[name,setName]=useState(''),[category,setCategory]=useState('Porches'),[price,setPrice]=useState(''),[desc,setDesc]=useState(''),[imageUrl,setImageUrl]=useState('');
 const refresh=async()=>{const [p,q,r,w]=await Promise.all([supabase.from('catalogo').select('*').order('orden'),supabase.from('solicitudes').select('*').order('created_at',{ascending:false}),supabase.from('resenas').select('*').order('created_at',{ascending:false}),supabase.from('trabajos_realizados').select('*').order('created_at',{ascending:false})]);setProducts(p.data||[]);setRequests(q.data||[]);setReviews(r.data||[]);setWorks(w.data||[])};
 const verify=async(ses)=>{if(!ses){setSession(null);setIsAdmin(false);setLoading(false);return}const {data}=await supabase.from('admins').select('user_id').eq('user_id',ses.user.id).maybeSingle();setSession(ses);setIsAdmin(!!data);if(data)await refresh();setLoading(false)};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>verify(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,ses)=>verify(ses));return()=>subscription.unsubscribe()},[]);
 const login=async()=>{setLoading(true);const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password:pass});if(error){setLoading(false);Alert.alert('Acceso denegado','Usuario o contraseña incorrectos.')}};
 const logout=()=>supabase.auth.signOut();
 const clearForm=()=>{setEdit(null);setName('');setCategory('Porches');setPrice('');setDesc('');setImageUrl('')};
 const pickImage=async()=>{const res=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.85});if(res.canceled)return;const asset=res.assets[0];try{const body=await (await fetch(asset.uri)).arrayBuffer();const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.jpg`;const {error}=await supabase.storage.from('catalogo').upload(path,body,{contentType:asset.mimeType||'image/jpeg'});if(error)throw error;const {data}=supabase.storage.from('catalogo').getPublicUrl(path);setImageUrl(data.publicUrl)}catch(e){Alert.alert('Error de imagen',e.message)}};
 const saveProduct=async()=>{if(!name)return Alert.alert('Falta el nombre');const payload={nombre:name,categoria:category,descripcion:desc||null,precio_desde:price?Number(String(price).replace(',','.')):null,imagen_url:imageUrl||null,activo:true};const op=edit?supabase.from('catalogo').update(payload).eq('id',edit.id):supabase.from('catalogo').insert(payload);const {error}=await op;if(error)return Alert.alert('Error',error.message);clearForm();await refresh()};
 const editProduct=p=>{setEdit(p);setName(p.nombre||'');setCategory(p.categoria||'Porches');setPrice(p.precio_desde?String(p.precio_desde):'');setDesc(p.descripcion||'');setImageUrl(p.imagen_url||'')};
 const delProduct=async p=>{const {error}=await supabase.from('catalogo').delete().eq('id',p.id);if(error)Alert.alert('Error',error.message);else refresh()};
 const setStatus=async(q,estado)=>{await supabase.from('solicitudes').update({estado,updated_at:new Date().toISOString()}).eq('id',q.id);refresh()};
 if(loading)return <Page><Loader/></Page>;
 if(!session||!isAdmin)return <Page><Text style={s.title}>Administración</Text><View style={s.card}><Text style={s.productName}>Acceso privado</Text><Text style={s.note}>Solo la cuenta autorizada puede modificar contenido y pedidos.</Text><Field placeholder="Email administrador" value={email} onChangeText={setEmail}/><Field placeholder="Contraseña" value={pass} onChangeText={setPass} secureTextEntry/><Btn title="Entrar" onPress={login}/></View></Page>;
 return <Page><Text style={s.title}>Panel de administración</Text><View style={s.tabs}>{['productos','pedidos','trabajos','reseñas'].map(x=><TouchableOpacity key={x} onPress={()=>setSection(x)} style={[s.tab,section===x&&s.tabOn]}><Text style={[s.tabText,section===x&&{color:'#fff'}]}>{x.toUpperCase()}</Text></TouchableOpacity>)}</View>
 {section==='productos'&&<><View style={s.card}><Text style={s.productName}>{edit?'Editar producto':'Añadir producto'}</Text><Field placeholder="Nombre" value={name} onChangeText={setName}/><Field placeholder="Categoría" value={category} onChangeText={setCategory}/><Field placeholder="Precio desde" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/><Field placeholder="Descripción" value={desc} onChangeText={setDesc} multiline/><Btn light title="Elegir imagen" onPress={pickImage}/>{imageUrl?<Image source={{uri:imageUrl}} style={s.productImage}/>:null}<Btn title={edit?'Guardar cambios':'Añadir producto'} onPress={saveProduct}/>{edit?<Btn light title="Cancelar edición" onPress={clearForm}/>:null}</View>{products.map(p=><View style={s.card} key={p.id}><Text style={s.productName}>{p.nombre}</Text><Text style={s.note}>{p.precio_desde?`${p.precio_desde} €`:'Sin precio'}</Text><Btn title="Editar" onPress={()=>editProduct(p)}/><Btn danger title="Eliminar" onPress={()=>delProduct(p)}/></View>)}</>}
 {section==='pedidos'&&requests.map(q=><View style={s.card} key={q.id}><Text style={s.productName}>{q.nombre} · {q.codigo_seguimiento}</Text><Text style={s.note}>{q.telefono} · {q.ciudad||''}</Text><Text style={s.note}>{q.tipo_trabajo||''}</Text><Text style={s.status}>{q.estado}</Text><Btn title="Presupuesto confirmado" onPress={()=>setStatus(q,'Presupuesto confirmado')}/><Btn light title="Fecha de instalación" onPress={()=>setStatus(q,'Fecha de instalación')}/><Btn light title="Porche instalado" onPress={()=>setStatus(q,'Porche instalado')}/><Btn title="WhatsApp cliente" onPress={()=>Linking.openURL(`https://wa.me/${String(q.telefono).replace(/\D/g,'')}`)}/></View>)}
 {section==='trabajos'&&<><View style={s.card}><Text style={s.note}>Los trabajos publicados en Supabase aparecen automáticamente en la galería. Desde esta versión puedes revisar los existentes; la carga avanzada se seguirá ampliando sin cambiar el acceso.</Text></View>{works.map(w=><View style={s.card} key={w.id}>{w.imagen_url?<Image source={{uri:w.imagen_url}} style={s.productImage}/>:null}<Text style={s.productName}>{w.titulo}</Text></View>)}</>}
 {section==='reseñas'&&reviews.map(r=><View style={s.card} key={r.id}><Text style={s.stars}>{'★'.repeat(r.estrellas)}</Text><Text style={s.review}>{r.texto}</Text><Text style={s.reviewName}>{r.nombre}</Text></View>)}
 <Btn light title="Actualizar datos" onPress={refresh}/><Btn danger title="Cerrar sesión" onPress={logout}/></Page>}

const Tab=createBottomTabNavigator();
export default function App(){return <NavigationContainer><StatusBar style="light"/><Tab.Navigator screenOptions={({route})=>({headerStyle:{backgroundColor:C.brown2},headerTintColor:'#fff',tabBarActiveTintColor:C.brown2,tabBarInactiveTintColor:'#8b817a',tabBarLabelStyle:{fontSize:9},tabBarIcon:({color,size})=>{const m={Inicio:'home',Catálogo:'grid',Trabajos:'images',Seguimiento:'git-branch',Reseñas:'star',Admin:'settings'};return <Ionicons name={m[route.name]} size={size} color={color}/>;}})}><Tab.Screen name="Inicio" component={Home}/><Tab.Screen name="Catálogo" component={Catalog}/><Tab.Screen name="Trabajos" component={Works}/><Tab.Screen name="Seguimiento" component={Tracking}/><Tab.Screen name="Reseñas" component={Reviews}/><Tab.Screen name="Admin" component={Admin}/></Tab.Navigator></NavigationContainer>}

const s=StyleSheet.create({body:{padding:14,paddingBottom:40},hero:{backgroundColor:'#2C160C',padding:24,borderRadius:18,alignItems:'center',marginBottom:18},kicker:{color:C.gold,fontWeight:'800',fontSize:12},hero1:{color:'#DCA54F',fontSize:26,fontWeight:'900',marginTop:12,textAlign:'center'},hero2:{color:'#fff',fontSize:34,fontWeight:'900'},heroSub:{color:'#eadfd6',marginVertical:12,textAlign:'center'},title:{fontSize:23,fontWeight:'900',color:C.brown,marginBottom:12},note:{color:C.muted,lineHeight:20,marginBottom:10},card:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:12,elevation:2},cardText:{color:C.ink,fontSize:16,fontWeight:'700'},btn:{backgroundColor:C.green,padding:13,borderRadius:10,alignItems:'center',marginTop:8},btnLight:{backgroundColor:C.cream,borderWidth:1,borderColor:C.gold},btnText:{color:'#fff',fontWeight:'900'},product:{backgroundColor:'#fff',padding:13,borderRadius:14,marginBottom:12},productImage:{height:190,borderRadius:11,backgroundColor:'#D1A56B',resizeMode:'cover',marginTop:8},productName:{fontSize:17,fontWeight:'900',color:C.brown,marginTop:8},price:{fontWeight:'900',color:C.green,marginTop:4},input:{borderWidth:1,borderColor:'#decdb9',backgroundColor:'#fff',borderRadius:9,padding:11,marginTop:9},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},work:{width:'48%',backgroundColor:'#fff',borderRadius:13,padding:8,marginBottom:12},workImg:{width:'100%',height:140,borderRadius:10,backgroundColor:'#D1A56B',resizeMode:'cover'},workTitle:{fontWeight:'900',color:C.brown,marginTop:7},workText:{fontWeight:'700',color:C.muted,marginTop:3},stars:{fontSize:24,color:'#D69B2D'},review:{fontSize:16,lineHeight:24,color:C.ink,marginVertical:8},reviewName:{fontWeight:'900',color:C.brown2},status:{fontSize:17,fontWeight:'900',color:C.green,marginVertical:6},tabs:{flexDirection:'row',flexWrap:'wrap',marginBottom:12},tab:{paddingVertical:9,paddingHorizontal:10,backgroundColor:'#fff',borderRadius:10,marginRight:6,marginBottom:6},tabOn:{backgroundColor:C.brown2},tabText:{fontWeight:'900',fontSize:11,color:C.brown}});
